import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import os

print("Starting Python ML Pipeline...")

# Step 1: Check if the C++ generated file exists
file_name = 'synthetic_housing_data.csv'

if not os.path.exists(file_name):
    print(f"Error: {file_name} not found! Please run data_engine.cpp first.")
    exit()

# Step 2: Load the data generated by C++
print(f"Loading data from {file_name}...")
df = pd.read_csv(file_name)

# Step 3: Preprocessing (handling any accidental missing values)
df.fillna(df.mean(), inplace=True)

# Step 4: Split features (X) and target (y)
X = df.drop('price_lakhs', axis=1)
y = df['price_lakhs']

# 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Train the Random Forest Model
print("Training Random Forest Regressor...")
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Step 6: Evaluate the model
predictions = rf_model.predict(X_test)
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("\n--- Pipeline Results ---")
print(f"Model Mean Absolute Error: {mae:.2f} Lakhs")
print(f"Model Accuracy (R2 Score): {r2:.2f}")
print("Pipeline execution finished successfully.")
